solids:
  create_dataframe:
    inputs:
      csv_path:
        value: "data/raw/comments_train.csv"
  prepare_grid_random_forest:
    inputs:
      key:
        value: 'RandomForestClassifier'
      param_grid:
        value: {"n_estimators": [5, 10],
                "max_features": ["auto"],
                "max_depth" : [1,2]}
  prepare_grid_logistic_regression:
    inputs:
      key:
        value: 'LogisticRegression'
      param_grid:
        value: {"penalty":["l2", "none"],
                "class_weight": ["balanced", "None"]}

